name: Cloudformation stack deploy for GuardDuty        
on:
#   push:
#     branches: issue_560
  workflow_dispatch:
jobs:
  cloudformation-stack-deploy:
    uses: clouddrove/github-shared-workflows/.github/workflows/deploy-cloudformation.yml@master
    with:  
      s3-bucket: 'cf-templates-x4tlk28liqb4-us-east-2'
      bucket-prefix: 'test-workflow'
      aws-region: 'us-east-2'
      stack-name: 'awsguardduty-enabler'
      template-path: aws-control-tower-guardduty-enabler.template
      GitHub-repo-name: aws-control-tower-guardduty-enabler
      GitHub-branch: issue_560
      code-folder: src
      organization-name: aws-controltower-examples
      zip-file-name: guardduty-enabler.zip
      parameter-overrides: SecurityAccountId=785981945575, OrganizationId=o-6z7qdjp2db, RegionFilter=ControlTower, S3SourceBucket=cf-templates-x4tlk28liqb4-us-east-2, S3SourceFile:=test-workflow/guardduty-enabler.zip, ComplianceFrequency=7, RoleToAssume=AWSControlTowerExecution
      # parameter-overrides: VpcName=MyCustom333,  CidrBlock=10.0.0.0/16
    secrets:
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      GITHUB: ${{ secrets.GITHUB }}
